server:
  port: 7778
spring:
  application:
    name: user
  datasource:
    #url: jdbc:mysql://10.80.151.108:3306/usersdb
    #url: jdbc:mysql://10.80.148.154:3306/usersdb
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
